import { FailedPayment } from "./types";

// Seeded, deterministic mock dataset simulating Razorpay failed-payment / subscription-renewal webhooks.
export const failedPayments: FailedPayment[] = [
  {
    id: "pay_F001",
    customerName: "Ananya Rao",
    customerEmail: "ananya.rao@example.com",
    customerPhone: "+91 98765 43210",
    amount: 1499,
    currency: "INR",
    planName: "Pro Monthly",
    failureReason: "insufficient_funds",
    failedAt: "2026-08-24T09:12:00Z",
    attemptNumber: 1,
    subscriptionId: "sub_A101",
    status: "failed",
    previousSuccessfulPayments: 6,
    customerTenureMonths: 6,
    preferredLanguage: "Hinglish",
  },
  {
    id: "pay_F002",
    customerName: "Rohit Malhotra",
    customerEmail: "rohit.m@example.com",
    customerPhone: "+91 91234 56780",
    amount: 4999,
    currency: "INR",
    planName: "Team Annual",
    failureReason: "card_expired",
    failedAt: "2026-08-23T15:40:00Z",
    attemptNumber: 2,
    subscriptionId: "sub_A102",
    status: "contacted",
    previousSuccessfulPayments: 11,
    customerTenureMonths: 14,
    preferredLanguage: "English",
  },
  {
    id: "pay_F003",
    customerName: "Priya Sundaram",
    customerEmail: "priya.s@example.com",
    customerPhone: "+91 90000 11223",
    amount: 799,
    currency: "INR",
    planName: "Starter Monthly",
    failureReason: "bank_decline",
    failedAt: "2026-08-25T11:05:00Z",
    attemptNumber: 1,
    subscriptionId: "sub_A103",
    status: "failed",
    previousSuccessfulPayments: 1,
    customerTenureMonths: 1,
    preferredLanguage: "Hindi",
  },
  {
    id: "pay_F004",
    customerName: "Karan Verma",
    customerEmail: "karan.verma@example.com",
    customerPhone: "+91 98111 22334",
    amount: 2499,
    currency: "INR",
    planName: "Pro Annual",
    failureReason: "issuer_unavailable",
    failedAt: "2026-08-22T07:30:00Z",
    attemptNumber: 1,
    subscriptionId: "sub_A104",
    status: "recovered",
    previousSuccessfulPayments: 9,
    customerTenureMonths: 10,
    preferredLanguage: "English",
  },
  {
    id: "pay_F005",
    customerName: "Sneha Kulkarni",
    customerEmail: "sneha.k@example.com",
    customerPhone: "+91 99887 76655",
    amount: 1999,
    currency: "INR",
    planName: "Pro Monthly",
    failureReason: "network_error",
    failedAt: "2026-08-25T18:20:00Z",
    attemptNumber: 1,
    subscriptionId: "sub_A105",
    status: "failed",
    previousSuccessfulPayments: 3,
    customerTenureMonths: 3,
    preferredLanguage: "Hinglish",
  },
  {
    id: "pay_F006",
    customerName: "Vikram Desai",
    customerEmail: "vikram.d@example.com",
    customerPhone: "+91 97654 32109",
    amount: 6999,
    currency: "INR",
    planName: "Team Annual",
    failureReason: "otp_timeout",
    failedAt: "2026-08-21T13:15:00Z",
    attemptNumber: 3,
    subscriptionId: "sub_A106",
    status: "lost",
    previousSuccessfulPayments: 2,
    customerTenureMonths: 2,
    preferredLanguage: "English",
  },
  {
    id: "pay_F007",
    customerName: "Meera Iyer",
    customerEmail: "meera.iyer@example.com",
    customerPhone: "+91 96543 21098",
    amount: 999,
    currency: "INR",
    planName: "Starter Monthly",
    failureReason: "insufficient_funds",
    failedAt: "2026-08-26T06:50:00Z",
    attemptNumber: 1,
    subscriptionId: "sub_A107",
    status: "failed",
    previousSuccessfulPayments: 0,
    customerTenureMonths: 0,
    preferredLanguage: "Hindi",
  },
  {
    id: "pay_F008",
    customerName: "Arjun Nair",
    customerEmail: "arjun.nair@example.com",
    customerPhone: "+91 95432 10987",
    amount: 3499,
    currency: "INR",
    planName: "Pro Annual",
    failureReason: "card_expired",
    failedAt: "2026-08-20T10:00:00Z",
    attemptNumber: 1,
    subscriptionId: "sub_A108",
    status: "recovered",
    previousSuccessfulPayments: 14,
    customerTenureMonths: 18,
    preferredLanguage: "English",
  },
  {
    id: "pay_F009",
    customerName: "Farhan Sheikh",
    customerEmail: "farhan.sheikh@example.com",
    customerPhone: "+91 93210 45678",
    amount: 1299,
    currency: "INR",
    planName: "Starter Monthly",
    failureReason: "bank_decline",
    failedAt: "2026-08-19T08:05:00Z",
    attemptNumber: 3,
    subscriptionId: "sub_A109",
    status: "failed",
    previousSuccessfulPayments: 0,
    customerTenureMonths: 1,
    preferredLanguage: "Hinglish",
  },
];

export function getPaymentById(id: string): FailedPayment | undefined {
  return failedPayments.find((p) => p.id === id);
}
