// AUTO-GENERATED by scripts/train-recoverability-model.mjs - do not hand-edit.
// Regenerate with: npm run train:model
//
// Trained on a synthetic labeled dataset (see the script for the labeling rule) since
// this buildathon build has no live payments account / real recovery outcome history.
// Precision/recall/AUC below are honest measurements against a held-out 20% split of
// that synthetic data - they describe how well the model learned the documented rule,
// not a claim about real-world recovery rates.

export const MODEL_WEIGHTS = {
  numericFeatures: ["attemptNumber","customerTenureMonths","previousSuccessfulPayments","amount"] as const,
  numericStats: {
  "attemptNumber": {
    "mean": 1.97125,
    "std": 0.8165007271889076
  },
  "customerTenureMonths": {
    "mean": 18.12,
    "std": 10.704933442109754
  },
  "previousSuccessfulPayments": {
    "mean": 10.083125,
    "std": 6.030958898415327
  },
  "amount": {
    "mean": 4222.524375,
    "std": 2173.234151134171
  }
},
  failureReasonCategories: ["insufficient_funds","card_expired","bank_decline","issuer_unavailable","network_error","otp_timeout"] as const,
  weights: [-1.0818918565123168,0.8995357353257123,0.7570734634910287,-0.27377748703802485,-0.08057485877480687,-0.09303822434715647,-0.29083154963545904,0.3163955015934966,0.3909235918871486,-0.22843728196860874],
  bias: 0.04097757096337904,
};

export const MODEL_METRICS = {
  precision: 0.7794871794871795,
  recall: 0.7755102040816326,
  accuracy: 0.7825,
  auc: 0.875375150060024,
  datasetSize: 2000,
  trainSize: 1600,
  testSize: 400,
  trainedAt: "2026-09-01T22:09:34.245Z",
};
